name: Text Generation Web UI
description: |
  This AMP demonstrates how to use an open source pre-trained instruction-following LLM (Large Language Model) to build a ChatBot-like web application.

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-04-22"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: Install Dependencies
    script: 1_session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 4
    memory: 16
  
  - type: start_application
    name: CML Text Generation 
    subdomain: cmlllm
    script: server.py
    short_summary: Start CML Text gen application
    long_summary: This application requires an available GPU to run the LLM model. Startup may be delayed if autoscaling is being performed or fail if GPU cannot be scheduled on this workspace. Please contact your administrator for GPU scheduling.
    cpu: 4
    memory: 16
    gpu: 1
    environment_variables:
      TASK_TYPE: START_APPLICATION
